// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUVs7qylVzYGMUnMJcOnuehifcuFSs6F8',
    appId: '1:223123144586:web:8e6fb48af3f0d9f3ad5273',
    messagingSenderId: '223123144586',
    projectId: 'trendvault-a71dd',
    authDomain: 'trendvault-a71dd.firebaseapp.com',
    storageBucket: 'trendvault-a71dd.appspot.com',
    measurementId: 'G-71FYXFD1ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu2AvF8HofwJeqmZOZi0b_1mudfU9Wl2E',
    appId: '1:223123144586:android:ff763878a8b7a99cad5273',
    messagingSenderId: '223123144586',
    projectId: 'trendvault-a71dd',
    storageBucket: 'trendvault-a71dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHZ4ZdAQoxR5GD1uWLRrDSWB22Cie-NSs',
    appId: '1:223123144586:ios:c82d0ce8c8988c68ad5273',
    messagingSenderId: '223123144586',
    projectId: 'trendvault-a71dd',
    storageBucket: 'trendvault-a71dd.appspot.com',
    iosBundleId: 'com.example.tStore',
  );
}
